version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    container_name: nginx116-php-xdebug
    ports:
    - 80:80
    volumes:
    - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: always
  database:
    image: mysql:5.7
    container_name: mysql57
    ports:
    - 3306:3306
    volumes:
    - ./mysql/dbdata/:/var/lib/mysql/
    - ./mysql/logs/:/var/log/
    environment:
        MYSQL_ROOT_PASSWORD: password
    restart: always
